name: belajar_api
description: "Moviex (OMDb) â€” browse film & tonton trailer."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  cached_network_image: ^3.4.1
  youtube_player_flutter: ^9.0.2
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # ðŸ”½ Tambahan untuk RILIS
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.3

flutter:
  uses-material-design: true

  assets:
    - assets/logo.jpg

# ===== Ikon Aplikasi (Android & iOS) =====
flutter_icons:
  android: true
  ios: true
  image_path: assets/logo.jpg
  adaptive_icon_background: "#0B0B0D"   # warna latar icon Android
  adaptive_icon_foreground: assets/logo.jpg

# ===== Splash Screen (Android & iOS) =====
flutter_native_splash:
  color: "#0B0B0D"
  image: assets/logo.jpg
  color_dark: "#0B0B0D"
  image_dark: assets/logo.jpg
  android_12:
    color: "#0B0B0D"
    image: assets/logo.jpg
    icon_background_color: "#0B0B0D"
